### ISSUE TITLE
Update the circle.yml file

### ISSUE THREAD

**Issue by chrishulton** [crowdtap/generator-crowdtap-angular#9]
1) Change the deployment command (use socialstars.admin circle.yml as an example)

```
- curl -XPOST http://deploy:20dca2067c57c415fd797184715b1b@deployer.crowdtap.us/deploys/$CIRCLE_PROJECT_REPONAME/production/$CIRCLE_SHA1
```

2) Add firefox install (copy install-firefox-30.sh from socialstars.admin)

```
set -x
set -e
if [ ! -e firefox ]; then
  #wget ftp://ftp.mozilla.org/pub/firefox/releases/30.0/linux-x86_64/en-US/firefox-30.0.tar.bz2
  wget https://s3.amazonaws.com/crowdtap-ci/firefox-30.0.tar.bz2
  tar -xjf firefox-30.0.tar.bz2
fi
sudo rm -rf  /opt/firefox
sudo rm -rf  /usr/bin/firefox
sudo cp -r firefox /opt/firefox30
sudo ln -s /opt/firefox30/firefox /usr/bin/firefox;
```

3) Update the dependencies (use socialstars.admin circle.yml as an example)

```
dependencies:
    cache_directories:
      - firefox
    pre:
      - bash ./install-firefox-30.sh
```
